#!/usr/bin/env bash

function build {
    echo "'!!! Building Library' && rm -rf lib && babel src --out-dir lib && node-sass src/lib/Timeline.scss lib/Timeline.css && sed -i'.bak' 's/Timeline\\.scss/Timeline\\.css/g' lib/lib/Timeline.js && rm lib/lib/Timeline.js.bak"
}

function main {
    exit_status=0
    build
    exit $exit_status
}

main "$@"