#!/usr/bin/env bash

function build {
    rm -rf lib && ./node_modules/.bin/babel src --out-dir lib && ./node_modules/.bin/node-sass src/lib/Timeline.scss lib/Timeline.css && sed -i'.bak' 's/Timeline\\.scss/Timeline\\.css/g' lib/lib/Timeline.js && rm lib/lib/Timeline.js.bak
}

function commit_changes {
    # Check if there are any changes to commit
    if [[ -n $(git status -s) ]]; then
        git add lib/*
        
        # Commit changes with a default message
        git commit -m "Build artifacts updated"
    else
        echo "No changes to commit."
    fi
}

function main {
    exit_status=0

    current_branch=$(git branch --show-current)
    if [ "$current_branch" = "main" ]; then
        build || exit_status=$?

        if [ $exit_status -eq 0 ]; then
            commit_changes
        fi

    fi

    if [ $exit_status -ne 0 ]; then
      echo "Pre-push hook failed (build failed)."
      exit $exit_status
    fi
}

main "$@"